name: Deploy to Cloudflare

on:
    push:
        branches:
            - main
            - dev

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies                                                                                                                                                                                                                                       .idea/workspace.xml          +17 -32
              run: npm ci                                                                                                                                                                                                                                                      .open-next/.build/open-next.c+148 -1
            - name: Build                                                                                                                                                                                                                                                      .open-next/.build/open-next.c+142 -1
              run: npm run diomerda
            - name: Deploy
              uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  command: deploy
                  wranglerVersion: "4.76.0"
